In [1]:
import numpy as np

### Generating a 3 by 3 matrix randomly from range 1-10
C =np.arange(1,10).reshape(3,3)
print(C)

### Generating a 3 by 3 matrix randomly from range 1-10
D = np.arange(1,10).reshape(3,3)
print(D)

### Smming the two matrix
matrix_sum = D + C
print('Sum:', matrix_sum)

### Multiplying the two matrix

matrix_mul = D*C
print('Multiplication : ' ,matrix_mul)

## transposeing D
D_Transpose = np.transpose(D)
print('Transpose:', D_Transpose)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum: [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Multiplication :  [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]
