### Project 9: Image Array Processing

In [1]:
import numpy as np

image = np.array([
    [50, 100, 150],
    [200, 250, 100],
    [25, 75, 125]
])

print(image)

bright_image = image + 50
print('Light image is:',bright_image)
bright_image = np.clip(image + 50, 0, 255)


dark_image = image - 30
dark_image = np.clip(dark_image, 0, 255)

print('Dark Image is :',dark_image)

[[ 50 100 150]
 [200 250 100]
 [ 25  75 125]]
Light image is: [[100 150 200]
 [250 300 150]
 [ 75 125 175]]
Dark Image is : [[ 20  70 120]
 [170 220  70]
 [  0  45  95]]
